platform :ios, '7.0'
use_frameworks!

target 'MKXOne' do
   pod 'Masonry', '~> 0.6.3'

   pod 'SDWebImage', '~> 3.7.3'

   pod 'MJExtension', '~> 3.0.7'

   pod 'MJRefresh', '~> 3.0.7'

   pod 'MBProgressHUD', '~> 0.9.1'

   pod 'AFNetworking', '~> 3.0.1'

   pod 'FMDB', '~> 2.5'

end
